# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The product index
email: joelalovera@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  An open and organized directory of the best pieces about Product Management.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://theproductindex.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: loverajoel
github_username:  loverajoel

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-timeago
  - jekyll-github-metadata
  - jekyll-last-modified-at

google_analytics: UA-144584240-1

repository: theproductindex/theproductindex.com

jekyll_timeago:
  depth: 1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
